version: '3.8'

services:
  file-manager:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=production
    restart: unless-stopped
